version: '3.8'

services:
  gitlab-reviewer:
    build: .
    ports:
      - "8080:80"
      - "3001:3001"
    volumes:
      # 持久化数据存储
      - ./data:/app/server/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      # API地址配置：
      # 1. 如果使用IP访问：http://your-server-ip:3001
      # 2. 如果使用域名访问：http://your-domain.com:3001 或 https://your-domain.com:3001
      # 3. 如果有反向代理：可以设置为相对路径或完整URL
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped
    container_name: gitlab-reviewer
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local 