version: '3.8'

services:
  gitlab-reviewer:
    build: .
    ports:
      - "8080:80"
      - "3001:3001"
    volumes:
      # 持久化数据存储
      - ./data:/app/server/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 可选：如果需要自定义API地址，取消注释下一行
      # - REACT_APP_API_URL=http://your-server-ip:3001
    restart: unless-stopped
    container_name: gitlab-reviewer
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local 